#%RAML 1.0 NamedExample
value:
  - ID: 1209
    firstName: Diego
    lastName: Gomez
    address: 432 MyAddress St
    postal: 94620
    country: Mex
    miles: 100
    creationDate: 102018
  - ID: 1215
    firstName: Patrick
    lastName: Gumble
    address: 77 Magin St
    postal: 94667
    country: Mex
    miles: 103
    creationDate: 102015